### ISSUE TITLE
hey i m wondering if you have any technology?

### ISSUE THREAD

**Issue by jimmylegget** [SecureCloudCoin/securecloudcoin#1]
have you guys developed any tech since those come from pivix and others

**Comment by albertcrombwie** [comment]
As specified in the website, whitepaper and many other place we had IMPLEMENTED several existing technologies mainly from Dash Pivx and Rupx (since we fork them....). If you are trying to understand if we are expert or not, the answer is YES, cause we have changed several place and several of these features and we implemented a new idea regarding reward schema for pos and masternode, and also made several modification into the QT wallet.

So we have the perfect knowledge, also in this field, since we are a real project, we are not just copying other projects as done by 99% of any existing masternode coin (mostly copied in a very bad way by person that don't know how to be a programmer).

btw... where is the issue? 😄
