### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [SecureCloudCoin/securecloudcoin#2]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository

File in question:

      securecloudcoin/LICENSE

**Comment by albertcrombwie** [comment]
we do not tolerate at all this kind of FUD.
the file you mentioned is not part of PIVX repository, not present at all.
As you can see we have not removed one of PIVX brand or logo, in order to be compliant with copyright and we also have added a link to PIVX project in our first page of the repository: the readme.
We started our project from RUPX and not PIVX, that have the file LICENCE that is identical of our file:

take a look here:
https://github.com/rupaya-project/rupaya/blob/master/LICENSE, rupaya is the committer of this file and PIVX is not mentioned at all.

As you can see in all files of our repository we leave the pivx copyright as is (and it is i think correct, and not just "necessary"), and also in the COPYING file (that as opposite of LICENSE file that is not commited, this is committed into your repository)

https://github.com/SecureCloudCoin/securecloudcoin/blob/master/COPYING

However just to close the discussion, since it's not a secret that we adopt several features of PIVX, nor something to hide (and we have nothing to hide at all in our project), please notice me how can we fix this problem and what do you expect to find inside that file (even if not present into PIVX repository), there will be no rush to change it to give to PIVX the expected evidence in that file.

By the way please navigate 99% of existing masternode coins and add the same comment you added to our repository. They all suffer of the same issue.

Thanks in advance for you response, I'm waiting for any further indication, to fix this issue

**Comment by Iconoclasta** [comment]
Hey thanks for the collaboration. 
The PIVX team will be paying closer attention for copyright violations, which will then allow healthier and mutual relationships with our various forks. We have plans of forming a network we can all mutually benefit from. I would love to keep you in the loop about such progress.

The issue we have found on yours and plenty other repositories is that you've apparently "re-licensed" our code, rather than "sub-licensed". This is so because there is a hierarchy in licensing files and `LICENSE` is higher than `COPYING` (please refer to this link to understand what I mean: https://i.imgur.com/l1MgVDo.gif ). To best address this issue I would recommend to either simply delete the `LICENSE` file (which currently adds no apparent value), or re-purpose the `LICENSE` file for a different copyright notice than MIT (Apache or GNU for example).

**Comment by albertcrombwie** [comment]
removed file as suggested by you and updated 

> 
      securecloudcoin/COPYING

If no more pending issues on copyright I'll close this issue in some days :)

**Comment by Iconoclasta** [comment]
Everything seems in order. We'll double check a few more of your source files and confirm your compliance.

**Comment by Iconoclasta** [comment]
Everything seems in order, thanks for the collaboration.
The PIVX team will be paying closer attention for copyright violations, which will then allow healthier and mutual relationships with our various forks. We have plans of forming a network we can all mutually benefit from. I would love to keep you in the loop about such progress.
